### PR TITLE
fix: support long command lines for all shells on Windows

### LINKED ISSUE #2041: Windows: The command line is (still) too long
**Describe the bug**

Pull request #2035 resolved the Windows error "The command line is too long" when a JBang Kotlin script is run from PowerShell or CMD. However the issue is still unresolved when the script is run from Bash on Windows.

**To Reproduce**

*Test01.sh* 

```bash
./build/install/jbang/bin/jbang version
./build/install/jbang/bin/jbang cache clear
./build/install/jbang/bin/jbang ./Test01.kt
```

```
wfouche@DESKTOP-IOB82O4 MINGW64 ~/IdeaProjects/jbang (main)
$ ./Test01.sh
0.126.1.12
[jbang] Clearing cache for urls
[jbang] Clearing cache for jars
[jbang] Clearing cache for kotlincs
[jbang] Clearing cache for groovycs
[jbang] Clearing cache for scripts
[jbang] Clearing cache for stdins
[jbang] Clearing cache for deps
[jbang] Downloading Kotlin 2.0.21. Be patient, this can take several minutes...
[jbang] Installing Kotlin 2.0.21...
[jbang] Resolving dependencies...
[jbang]    org.springframework.boot:spring-boot-starter-web:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-test:3.4.6
[jbang]    org.springframework.boot:spring-boot-configuration-processor:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-activemq:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-actuator:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-amqp:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-aop:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-artemis:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-batch:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-cache:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-cassandra:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-cassandra-reactive:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-couchbase:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-couchbase-reactive:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-elasticsearch:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-jdbc:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-jpa:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-ldap:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-mongodb:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-mongodb-reactive:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-neo4j:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-r2dbc:3.4.6
[jbang]    org.jetbrains.kotlin:kotlin-stdlib:2.0.21
[jbang] Dependencies resolved
[jbang] Building jar for Test01.kt...
The command line is too long.
[jbang] [ERROR] Error during compile
```

**JBang version**

Main branch, 0.126.12

**Additional information**

*Test01.kt*

```Kotlin
///usr/bin/env jbang "$0" "$@" ; exit $?

//DEPS org.springframework.boot:spring-boot-starter-web:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-test:3.4.6
//DEPS org.springframework.boot:spring-boot-configuration-processor:3.4.6
//DEPS org.springframework.boot:spring-boot-starter:3.4.6
//DEPS org.springframework.boot:spring-boot-starter:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-activemq:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-actuator:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-amqp:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-aop:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-artemis:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-batch:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-cache:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-data-cassandra:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-data-cassandra-reactive:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-data-couchbase:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-data-couchbase-reactive:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-data-elasticsearch:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-data-jdbc:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-data-jpa:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-data-ldap:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-data-mongodb:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-data-mongodb-reactive:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-data-neo4j:3.4.6
//DEPS org.springframework.boot:spring-boot-starter-data-r2dbc:3.4.6

fun main(args: Array<String>) {
    println("Kotlin: Hello World");
}
```

*Test01.cmd*

```
call .\build\install\jbang\bin\jbang version
call .\build\install\jbang\bin\jbang cache clear
call .\build\install\jbang\bin\jbang .\Test01.kt
```

*Test01.cmd - output*

```
0.126.1.12
[jbang] Clearing cache for urls
[jbang] Clearing cache for jars
[jbang] Clearing cache for kotlincs
[jbang] Clearing cache for groovycs
[jbang] Clearing cache for scripts
[jbang] Clearing cache for stdins
[jbang] Clearing cache for deps
[jbang] Downloading Kotlin 2.0.21. Be patient, this can take several minutes...
[jbang] Installing Kotlin 2.0.21...
[jbang] Resolving dependencies...
[jbang]    org.springframework.boot:spring-boot-starter-web:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-test:3.4.6
[jbang]    org.springframework.boot:spring-boot-configuration-processor:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-activemq:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-actuator:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-amqp:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-aop:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-artemis:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-batch:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-cache:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-cassandra:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-cassandra-reactive:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-couchbase:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-couchbase-reactive:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-elasticsearch:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-jdbc:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-jpa:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-ldap:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-mongodb:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-mongodb-reactive:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-neo4j:3.4.6
[jbang]    org.springframework.boot:spring-boot-starter-data-r2dbc:3.4.6
[jbang]    org.jetbrains.kotlin:kotlin-stdlib:2.0.21
[jbang] Dependencies resolved
[jbang] Building jar for Test01.kt...
Kotlin: Hello World
```

### PR DESCRIPTION
**Pull request by wfouche**
Fixes #2041

### CODE REVIEW

**Comment by wfouche** [comment]
Two tests are failing due to issues with host `xam.dk`.

```
dev.jbang.cli.ExitException: Could not download https://xam.dk/jbang-catalog.json
> java.net.ConnectException: Connection timed out (Connection timed out)
```

File: src/main/java/dev/jbang/util/CommandBuffer.java [hunk 1]
```diff
@@ -86,8 +86,7 @@ public CommandBuffer usingArgsFile() throws IOException {
 
 	public CommandBuffer applyWindowsMaxLengthLimit() throws IOException {
 		int maxLength = MAX_LENGTH_WINPROCBUILDER;
-		String cmd = arguments.get(0).toLowerCase();
-		if (cmd.endsWith(".bat") || cmd.endsWith(".cmd")) {
+		if (Util.isWindows()) {
```
Comment (quintesse) [inline src/main/java/dev/jbang/util/CommandBuffer.java]: This is unfortunately not correct. Basically what you're doing here is _always_ use the shortest value on Windows, regardless if that is really necessary or not.

**Review by quintesse — CHANGES_REQUESTED** [review]

File: src/test/java/dev/jbang/util/TestCommandBuffer.java [hunk 2]
```diff
@@ -45,16 +45,18 @@ void testRunWinPS1() {
...
 			.applyWindowsMaxLengthLimit()
 			.asProcessBuilder();
-		assertThat(pb.command().size(), greaterThan(2));
-		assertThat(pb.command().get(1), not(anyOf(startsWith("@"), startsWith("\"@"))));
+		assertThat(pb.command().size(), equalTo(2));
+		assertThat(pb.command().get(1), anyOf(startsWith("@"), startsWith("\"@")));
 	}
 
 	@Test
+	@EnabledOnOs(OS.WINDOWS)
```
Comment (quintesse) [inline src/test/java/dev/jbang/util/TestCommandBuffer.java:82]: This limit is not necessary, the test will work on any platform, even if it's meant for Windows

File: src/test/java/dev/jbang/util/TestCommandBuffer.java [hunk 3]
```diff
@@ -45,16 +45,18 @@ void testRunWinPS1() {
...
 	void testApplyWindowsMaxLengthLimitExe() throws IOException {
 		ProcessBuilder pb = CommandBuffer.of(argsTooLong("foo.exe"))
 			.shell(Util.Shell.cmd)
 			.applyWindowsMaxLengthLimit()
 			.asProcessBuilder();
-		assertThat(pb.command().size(), greaterThan(2));
-		assertThat(pb.command().get(1), not(anyOf(startsWith("@"), startsWith("\"@"))));
+		assertThat(pb.command().size(), equalTo(2));
```
Comment (quintesse) [inline src/test/java/dev/jbang/util/TestCommandBuffer.java:66]: This is wrong. The test is exactly meant to show that it is not necessary to use the @argFiles for executables.

File: src/test/java/dev/jbang/util/TestCommandBuffer.java (hunk 2 above)
Comment (quintesse) [reply src/test/java/dev/jbang/util/TestCommandBuffer.java:82]: Ah, but of course with your changes, it _is_ necessary. Forget I said anything :-)

**Comment by quintesse** [comment]
@wfouche sorry for taking over your PR again. I hope that's okay just to get these fixes in ASAP.

Could you perhaps test that it works now in all cases on your system?

**Comment by wfouche** [comment]
> Could you perhaps test that it works now in all cases on your system?

@quintesse  , thanks for jumping in. It helped to get the issue resolved quickly.

I fetched your changes,  made a new build and re-ran all my tests. They are all fine.

**Review by maxandersen — APPROVED** [review]
lgtm
