### PR TITLE
fix: Not duplicating or misquoting java options anymore

### LINKED ISSUE #786: Improper JAVA_OPTIONS handling
Issue #782 shows that there is some problem with the handling of JAVA_OPTIONS:

```
[jbang] run: /opt/data/sfw/tools/sdkman/candidates/java/current/bin/java '-Djava.util.logging.manager=org.jboss.logmanager.LogManager -Djava.util.logging.manager=org.jboss.logmanager.LogManager' -classpath ... '-Djava.util.logging.manager=org.jboss.logmanager.LogManager -Djava.util.logging.manager=org.jboss.logmanager.LogManager' io.quarkus.runner.GeneratedMain
```

The options appear quadrupled!

The main reason we're seeing this is because the script activates the Quarkus integration which causes a) the duplication of the options and b) making the options appear both at the start of the command as well as the end.

But it also shows a second problem where multiple options are quoted as if they were a single argument.

### PR DESCRIPTION
**Pull request by quintesse**
Fixes #786

### CODE REVIEW

File: src/main/java/dev/jbang/cli/BaseBuildCommand.java [hunk 1]
```diff
@@ -329,8 +329,10 @@ static void createJarFile(ScriptSource src, RunContext ctx, File path, File outp
 			}
 		}
 
-		String runtimeOpts = Stream	.concat(src.getRuntimeOptions().stream(), ctx.getPersistentJvmArgs().stream())
-									.collect(Collectors.joining(" "));
+		// When persistent JVM args are set they override any runtime options set on the
```
Comment (maxandersen) [inline src/main/java/dev/jbang/cli/BaseBuildCommand.java:332]: are they no longer persistent ?

Comment (quintesse) [reply src/main/java/dev/jbang/cli/BaseBuildCommand.java:332]: yes, but all runtime options are always persistent, so it wasn't really necessary to give them different names
