### PR TITLE
fix: Fixes NPE when running in container

### LINKED ISSUE #1653: console read NPE's in container with no terminal associated
I'm trying to make a new docker image for jbang that is simpler than current jbang-action and hit this issue:

```
[jbang] [0:469] Type in your choice and hit enter. Will automatically select option (0) after 30 seconds.
[jbang] [0:472] [ERROR] public class java.lang.NullPointerException
java.lang.NullPointerException
        at dev.jbang.util.ConsoleInput.readLine(ConsoleInput.java:71)
        at dev.jbang.util.Util.askInput(Util.java:1774)
        at dev.jbang.source.resolvers.RemoteResourceResolver.fetchScriptFromUntrustedURL(RemoteResourceResolver.java:69)
        at dev.jbang.source.resolvers.RemoteResourceResolver.resolve(RemoteResourceResolver.java:42)
        at dev.jbang.source.resolvers.CombinedResourceResolver.lambda$resolve$0(CombinedResourceResolver.java:27)
```

simply running `jbang quarkusinfo@maxandersen` from within a container with no terminal.

we should not NPE.

### PR DESCRIPTION
**Pull request by quintesse**
Fixes #1653

### CODE REVIEW

File: src/main/java/dev/jbang/util/ConsoleInput.java [hunk 1]
```diff
@@ -68,11 +84,9 @@ public String readLine() {
 					input = result.get(timeout, unit);
 					break;
 				} catch (ExecutionException | IOException e) {
-					e.getCause().printStackTrace();
+					Util.verboseMsg("/dev/tty is not available");
```
Comment (maxandersen) [inline src/main/java/dev/jbang/util/ConsoleInput.java:87]: It won't still make sense to print exception if in verbose mode ?

**Review by maxandersen — CHANGES_REQUESTED** [review]
Looks good but many print exception on verbose?

File: src/main/java/dev/jbang/util/ConsoleInput.java (hunk 1 above)
Comment (quintesse) [reply src/main/java/dev/jbang/util/ConsoleInput.java:87]: Sure

**Review by maxandersen — APPROVED** [review]
