### PR TITLE
fix: long classpath problem on Windows

### LINKED ISSUE #476: Cannot run Quarkus CLI on windows
I tried to run Quarkus CLI through jbang using the following command:

`jbang io.quarkus:quarkus-cli:1.9.1.Final:runner`

However, I don't get any output from the CLI, only from jbang:

```
[jbang] Resolving dependencies...
[jbang]     Resolving io.quarkus:quarkus-cli:1.9.1.Final:runner...Done
[jbang] Dependencies resolved
```
I tried with the `--verbose` flag:

```
[jbang] Resolving dependencies...                                                                                                                                                              
[jbang]     Resolving io.quarkus:quarkus-cli:1.9.1.Final:runner...Done                                                                                                                         
[jbang] Dependencies resolved                                                                                                                                                                  
[jbang] System Java version detected as 11                                                                                                                                                     
[jbang] System Java version matches requested version 11                                                                                                                                       
[jbang] run: ^"C:\apps\AdoptaJDK\openjdk\jdk-11.0.8+10\bin\java.exe^" -classpath ^"C:\Users\JeffMAURY\.m2\repository\io\quarkus\quarkus-cli\1.9.1.Final\quarkus-cli-1.9.1.Final-runner.jar;C:\U
sers\JeffMAURY\.m2\repository\io\quarkus\quarkus-picocli\1.9.1.Final\quarkus-picocli-1.9.1.Final.jar;C:\Users\JeffMAURY\.m2\repository\io\quarkus\quarkus-core\1.9.1.Final\quarkus-core-1.9.1.F
inal.jar;C:\Users\JeffMAURY\.m2\repository\jakarta\annotation\jakarta.annotation-api\1.3.5\jakarta.annotation-api-1.3.5.jar;C:\Users\JeffMAURY\.m2\repository\jakarta\inject\jakarta.inject-api
\1.0\jakarta.inject-api-1.0.jar;C:\Users\JeffMAURY\.m2\repository\io\quarkus\quarkus-ide-launcher\1.9.1.Final\quarkus-ide-launcher-1.9.1.Final.jar;C:\Users\JeffMAURY\.m2\repository\io\quarkus
\quarkus-development-mode-spi\1.9.1.Final\quarkus-development-mode-spi-1.9.1.Final.jar;C:\Users\JeffMAURY\.m2\repository\io\smallrye\config\smallrye-config\1.9.3\smallrye-config-1.9.3.jar;C:\
Users\JeffMAURY\.m2\repository\io\smallrye\common\smallrye-common-annotation\1.4.0\smallrye-common-annotation-1.4.0.jar;C:\Users\JeffMAURY\.m2\repository\io\smallrye\config\smallrye-config-co
mmon\1.9.3\smallrye-config-common-1.9.3.jar;C:\Users\JeffMAURY\.m2\repository\org\eclipse\microprofile\config\microprofile-config-api\1.4\microprofile-config-api-1.4.jar;C:\Users\JeffMAURY\.m
2\repository\io\smallrye\common\smallrye-common-expression\1.4.0\smallrye-common-expression-1.4.0.jar;C:\Users\JeffMAURY\.m2\repository\io\smallrye\common\smallrye-common-function\1.4.0\small
rye-common-function-1.4.0.jar;C:\Users\JeffMAURY\.m2\repository\io\smallrye\common\smallrye-common-constraint\1.4.0\smallrye-common-constraint-1.4.0.jar;C:\Users\JeffMAURY\.m2\repository\io\s
mallrye\common\smallrye-common-classloader\1.4.0\smallrye-common-classloader-1.4.0.jar;C:\Users\JeffMAURY\.m2\repository\org\ow2\asm\asm\8.0.1\asm-8.0.1.jar;C:\Users\JeffMAURY\.m2\repository\
org\jboss\logmanager\jboss-logmanager-embedded\1.0.5\jboss-logmanager-embedded-1.0.5.jar;C:\Users\JeffMAURY\.m2\repository\org\jboss\logging\jboss-logging-annotations\2.1.0.Final\jboss-loggin
g-annotations-2.1.0.Final.jar;C:\Users\JeffMAURY\.m2\repository\org\jboss\threads\jboss-threads\3.1.1.Final\jboss-threads-3.1.1.Final.jar;C:\Users\JeffMAURY\.m2\repository\org\slf4j\slf4j-api
\1.7.30\slf4j-api-1.7.30.jar;C:\Users\JeffMAURY\.m2\repository\org\jboss\slf4j\slf4j-jboss-logging\1.2.0.Final\slf4j-jboss-logging-1.2.0.Final.jar;C:\Users\JeffMAURY\.m2\repository\org\graalv
m\sdk\graal-sdk\20.2.0\graal-sdk-20.2.0.jar;C:\Users\JeffMAURY\.m2\repository\org\wildfly\common\wildfly-common\1.5.4.Final-format-001\wildfly-common-1.5.4.Final-format-001.jar;C:\Users\JeffM
AURY\.m2\repository\io\quarkus\quarkus-bootstrap-runner\1.9.1.Final\quarkus-bootstrap-runner-1.9.1.Final.jar;C:\Users\JeffMAURY\.m2\repository\io\quarkus\quarkus-arc\1.9.1.Final\quarkus-arc-1
.9.1.Final.jar;C:\Users\JeffMAURY\.m2\repository\io\quarkus\arc\arc\1.9.1.Final\arc-1.9.1.Final.jar;C:\Users\JeffMAURY\.m2\repository\jakarta\transaction\jakarta.transaction-api\1.3.3\jakarta
.transaction-api-1.3.3.jar;C:\Users\JeffMAURY\.m2\repository\org\eclipse\microprofile\context-propagation\microprofile-context-propagation-api\1.0.1\microprofile-context-propagation-api-1.0.1
.jar;C:\Users\JeffMAURY\.m2\repository\info\picocli\picocli\4.5.1\picocli-4.5.1.jar;C:\Users\JeffMAURY\.m2\repository\io\quarkus\quarkus-devtools-common\1.9.1.Final\quarkus-devtools-common-1.
9.1.Final.jar;C:\Users\JeffMAURY\.m2\repository\io\quarkus\quarkus-bootstrap-maven-resolver\1.9.1.Final\quarkus-bootstrap-maven-resolver-1.9.1.Final.jar;C:\Users\JeffMAURY\.m2\repository\io\q
uarkus\quarkus-bootstrap-app-model\1.9.1.Final\quarkus-bootstrap-app-model-1.9.1.Final.jar;C:\Users\JeffMAURY\.m2\repository\org\jboss\logging\commons-logging-jboss-logging\1.0.0.Final\common
s-logging-jboss-logging-1.0.0.Final.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\maven\maven-embedder\3.6.3\maven-embedder-3.6.3.jar;C:\Users\JeffMAURY\.m2\repository\commons-cli\commons-
cli\1.4\commons-cli-1.4.jar;C:\Users\JeffMAURY\.m2\repository\org\eclipse\sisu\org.eclipse.sisu.plexus\0.3.4\org.eclipse.sisu.plexus-0.3.4.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\mav
en\maven-settings-builder\3.6.3\maven-settings-builder-3.6.3.jar;C:\Users\JeffMAURY\.m2\repository\org\codehaus\plexus\plexus-interpolation\1.25\plexus-interpolation-1.25.jar;C:\Users\JeffMAU
RY\.m2\repository\org\sonatype\plexus\plexus-sec-dispatcher\1.4\plexus-sec-dispatcher-1.4.jar;C:\Users\JeffMAURY\.m2\repository\org\sonatype\plexus\plexus-cipher\1.4\plexus-cipher-1.4.jar;C:\
Users\JeffMAURY\.m2\repository\org\apache\maven\maven-resolver-provider\3.6.3\maven-resolver-provider-3.6.3.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\maven\resolver\maven-resolver-conn
ector-basic\1.4.1\maven-resolver-connector-basic-1.4.1.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\maven\resolver\maven-resolver-transport-wagon\1.4.1\maven-resolver-transport-wagon-1.4.
1.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\maven\wagon\wagon-http\3.3.4\wagon-http-3.3.4.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\maven\wagon\wagon-http-shared\3.3.4\wagon-htt
p-shared-3.3.4.jar;C:\Users\JeffMAURY\.m2\repository\org\jsoup\jsoup\1.12.1\jsoup-1.12.1.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\httpcomponents\httpclient\4.5.9\httpclient-4.5.9.jar;
C:\Users\JeffMAURY\.m2\repository\commons-codec\commons-codec\1.11\commons-codec-1.11.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\httpcomponents\httpcore\4.4.11\httpcore-4.4.11.jar;C:\Us
ers\JeffMAURY\.m2\repository\org\apache\maven\wagon\wagon-provider-api\3.3.4\wagon-provider-api-3.3.4.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\maven\wagon\wagon-file\3.3.4\wagon-file-
3.3.4.jar;C:\Users\JeffMAURY\.m2\repository\io\quarkus\quarkus-devtools-utilities\1.9.1.Final\quarkus-devtools-utilities-1.9.1.Final.jar;C:\Users\JeffMAURY\.m2\repository\io\quarkus\quarkus-d
evtools-codestarts\1.9.1.Final\quarkus-devtools-codestarts-1.9.1.Final.jar;C:\Users\JeffMAURY\.m2\repository\io\quarkus\quarkus-devtools-message-writer\1.9.1.Final\quarkus-devtools-message-wr
iter-1.9.1.Final.jar;C:\Users\JeffMAURY\.m2\repository\commons-io\commons-io\2.8.0\commons-io-2.8.0.jar;C:\Users\JeffMAURY\.m2\repository\io\quarkus\qute\qute-generator\1.9.1.Final\qute-gener
ator-1.9.1.Final.jar;C:\Users\JeffMAURY\.m2\repository\io\quarkus\qute\qute-core\1.9.1.Final\qute-core-1.9.1.Final.jar;C:\Users\JeffMAURY\.m2\repository\io\smallrye\reactive\mutiny\0.9.0\muti
ny-0.9.0.jar;C:\Users\JeffMAURY\.m2\repository\org\reactivestreams\reactive-streams\1.0.3\reactive-streams-1.0.3.jar;C:\Users\JeffMAURY\.m2\repository\io\quarkus\gizmo\gizmo\1.0.4.Final\gizmo
-1.0.4.Final.jar;C:\Users\JeffMAURY\.m2\repository\org\ow2\asm\asm-util\8.0.1\asm-util-8.0.1.jar;C:\Users\JeffMAURY\.m2\repository\org\ow2\asm\asm-tree\8.0.1\asm-tree-8.0.1.jar;C:\Users\JeffM
AURY\.m2\repository\org\ow2\asm\asm-analysis\8.0.1\asm-analysis-8.0.1.jar;C:\Users\JeffMAURY\.m2\repository\org\jboss\jandex\2.1.3.Final\jandex-2.1.3.Final.jar;C:\Users\JeffMAURY\.m2\reposito
ry\io\quarkus\quarkus-platform-descriptor-api\1.9.1.Final\quarkus-platform-descriptor-api-1.9.1.Final.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\maven\maven-model\3.6.3\maven-model-3.6.
3.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\commons\commons-compress\1.20\commons-compress-1.20.jar;C:\Users\JeffMAURY\.m2\repository\io\fabric8\maven-model-helper\16\maven-model-helpe
r-16.jar;C:\Users\JeffMAURY\.m2\repository\org\jdom\jdom\1.1.3\jdom-1.1.3.jar;C:\Users\JeffMAURY\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.11.3\jackson-databind-2.11.3.jar;
C:\Users\JeffMAURY\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.11.3\jackson-annotations-2.11.3.jar;C:\Users\JeffMAURY\.m2\repository\com\fasterxml\jackson\core\jackson-cor
e\2.11.3\jackson-core-2.11.3.jar;C:\Users\JeffMAURY\.m2\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-yaml\2.11.3\jackson-dataformat-yaml-2.11.3.jar;C:\Users\JeffMAURY\.m2\re
pository\org\yaml\snakeyaml\1.26\snakeyaml-1.26.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\maven\maven-plugin-api\3.6.3\maven-plugin-api-3.6.3.jar;C:\Users\JeffMAURY\.m2\repository\org\
apache\maven\maven-artifact\3.6.3\maven-artifact-3.6.3.jar;C:\Users\JeffMAURY\.m2\repository\org\codehaus\plexus\plexus-utils\3.2.1\plexus-utils-3.2.1.jar;C:\Users\JeffMAURY\.m2\repository\or
g\apache\maven\maven-core\3.6.3\maven-core-3.6.3.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\maven\maven-settings\3.6.3\maven-settings-3.6.3.jar;C:\Users\JeffMAURY\.m2\repository\org\apa
che\maven\maven-builder-support\3.6.3\maven-builder-support-3.6.3.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\maven\maven-repository-metadata\3.6.3\maven-repository-metadata-3.6.3.jar;C:
\Users\JeffMAURY\.m2\repository\org\apache\maven\maven-model-builder\3.6.3\maven-model-builder-3.6.3.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\maven\resolver\maven-resolver-impl\1.4.1\
maven-resolver-impl-1.4.1.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\maven\resolver\maven-resolver-api\1.4.1\maven-resolver-api-1.4.1.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\ma
ven\resolver\maven-resolver-spi\1.4.1\maven-resolver-spi-1.4.1.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\maven\resolver\maven-resolver-util\1.4.1\maven-resolver-util-1.4.1.jar;C:\Users
\JeffMAURY\.m2\repository\org\apache\maven\shared\maven-shared-utils\3.2.1\maven-shared-utils-3.2.1.jar;C:\Users\JeffMAURY\.m2\repository\org\eclipse\sisu\org.eclipse.sisu.inject\0.3.4\org.ec
lipse.sisu.inject-0.3.4.jar;C:\Users\JeffMAURY\.m2\repository\com\google\inject\guice\4.2.1\guice-4.2.1-no_aop.jar;C:\Users\JeffMAURY\.m2\repository\aopalliance\aopalliance\1.0\aopalliance-1.
0.jar;C:\Users\JeffMAURY\.m2\repository\com\google\guava\guava\25.1-android\guava-25.1-android.jar;C:\Users\JeffMAURY\.m2\repository\org\checkerframework\checker-compat-qual\2.0.0\checker-com
pat-qual-2.0.0.jar;C:\Users\JeffMAURY\.m2\repository\com\google\errorprone\error_prone_annotations\2.1.3\error_prone_annotations-2.1.3.jar;C:\Users\JeffMAURY\.m2\repository\com\google\j2objc\
j2objc-annotations\1.1\j2objc-annotations-1.1.jar;C:\Users\JeffMAURY\.m2\repository\org\codehaus\mojo\animal-sniffer-annotations\1.14\animal-sniffer-annotations-1.14.jar;C:\Users\JeffMAURY\.m
2\repository\org\codehaus\plexus\plexus-classworlds\2.6.0\plexus-classworlds-2.6.0.jar;C:\Users\JeffMAURY\.m2\repository\org\codehaus\plexus\plexus-component-annotations\2.1.0\plexus-componen
t-annotations-2.1.0.jar;C:\Users\JeffMAURY\.m2\repository\org\apache\commons\commons-lang3\3.8.1\commons-lang3-3.8.1.jar;C:\Users\JeffMAURY\.m2\repository\jakarta\enterprise\jakarta.enterpris
e.cdi-api\2.0.2\jakarta.enterprise.cdi-api-2.0.2.jar;C:\Users\JeffMAURY\.m2\repository\jakarta\el\jakarta.el-api\3.0.3\jakarta.el-api-3.0.3.jar;C:\Users\JeffMAURY\.m2\repository\jakarta\inter
ceptor\jakarta.interceptor-api\1.2.5\jakarta.interceptor-api-1.2.5.jar;C:\Users\JeffMAURY\.m2\repository\jakarta\ejb\jakarta.ejb-api\3.2.6\jakarta.ejb-api-3.2.6.jar;C:\Users\JeffMAURY\.m2\rep
ository\io\quarkus\http\quarkus-http-websockets-jsr\3.0.15.Final\quarkus-http-websockets-jsr-3.0.15.Final.jar;C:\Users\JeffMAURY\.m2\repository\io\quarkus\http\quarkus-http-core\3.0.15.Final\
quarkus-http-core-3.0.15.Final.jar;C:\Users\JeffMAURY\.m2\repository\io\quarkus\http\quarkus-http-http-core\3.0.15.Final\quarkus-http-http-core-3.0.15.Final.jar;C:\Users\JeffMAURY\.m2\reposit
ory\io\netty\netty-buffer\4.1.49.Final\netty-buffer-4.1.49.Final.jar;C:\Users\JeffMAURY\.m2\repository\io\netty\netty-codec-http\4.1.49.Final\netty-codec-http-4.1.49.Final.jar;C:\Users\JeffMA
URY\.m2\repository\io\netty\netty-common\4.1.49.Final\netty-common-4.1.49.Final.jar;C:\Users\JeffMAURY\.m2\repository\io\netty\netty-transport\4.1.49.Final\netty-transport-4.1.49.Final.jar;C:
\Users\JeffMAURY\.m2\repository\io\netty\netty-resolver\4.1.49.Final\netty-resolver-4.1.49.Final.jar;C:\Users\JeffMAURY\.m2\repository\io\netty\netty-codec\4.1.49.Final\netty-codec-4.1.49.Fin
al.jar;C:\Users\JeffMAURY\.m2\repository\io\netty\netty-handler\4.1.49.Final\netty-handler-4.1.49.Final.jar;C:\Users\JeffMAURY\.m2\repository\io\quarkus\http\quarkus-http-servlet\3.0.15.Final
\quarkus-http-servlet-3.0.15.Final.jar;C:\Users\JeffMAURY\.m2\repository\org\jboss\spec\javax\annotation\jboss-annotations-api_1.2_spec\1.0.2.Final\jboss-annotations-api_1.2_spec-1.0.2.Final.
jar;C:\Users\JeffMAURY\.m2\repository\jakarta\servlet\jakarta.servlet-api\4.0.3\jakarta.servlet-api-4.0.3.jar;C:\Users\JeffMAURY\.m2\repository\jakarta\websocket\jakarta.websocket-api\1.1.2\j
akarta.websocket-api-1.1.2.jar;C:\Users\JeffMAURY\.m2\repository\io\quarkus\quarkus-platform-descriptor-json\1.9.1.Final\quarkus-platform-descriptor-json-1.9.1.Final.jar;C:\Users\JeffMAURY\.m
2\repository\io\quarkus\quarkus-bom-descriptor-json\1.9.1.Final\quarkus-bom-descriptor-json-1.9.1.Final.json;C:\Users\JeffMAURY\.m2\repository\io\quarkus\quarkus-platform-descriptor-resolver-
json\1.9.1.Final\quarkus-platform-descriptor-resolver-json-1.9.1.Final.jar;C:\Users\JeffMAURY\.m2\repository\org\jboss\logging\jboss-logging\3.3.2.Final\jboss-logging-3.3.2.Final.jar^" io.qua
rkus.runner.GeneratedMain                                                                                                                                                                      
```
Seems to be that it is somehow related to the length of the command line but I'm surprised no error is reported

### PR DESCRIPTION
**Pull request by tivrfoa**
It uses @argument file if it's Windows and Java version >= 9

fixes #476

### CODE REVIEW

**Review by quintesse — CHANGES_REQUESTED** [review]
Personally I think we should put _all_ arguments in that file, not just the class path arguments,

File: src/main/java/dev/jbang/cli/Run.java [hunk 1]
```diff
@@ -210,8 +212,20 @@ String generateCommandLine(Script script) throws IOException {
...
 		}
 
-		return String.join(" ", escapeArguments(fullArgs));
+		final String args = String.join(" ", escapeArguments(fullArgs));
 
+		// This avoids long classpath problem on Windows.
+		// @file is only available from java 9 onwards.
+		if (Util.isWindows() && JavaUtil.determineJavaVersion() >= 9) {
+			final String jarFile = script.getJar().toString();
+			final String argsFile = jarFile.substring(0, jarFile.length() - 3) + "args";
```
Comment (quintesse) [inline src/main/java/dev/jbang/cli/Run.java:221]: As discussed on Gitter using a fixed file name is not really correct as different concurrent executions might be happening at the same time. So it should be a proper temp file.

**Review by quintesse — CHANGES_REQUESTED** [review]

File: src/main/java/dev/jbang/Script.java [hunk 2]
```diff
@@ -658,4 +659,12 @@ public String getJavaAgentOption() {
 		return agentOptions;
 	}
 
+	public File getArgs() {
```
Comment (maxandersen) [inline src/main/java/dev/jbang/Script.java:662]: this seems unnecessary to store on the script ?

File: src/test/java/dev/jbang/cli/TestRun.java [hunk 3]
```diff
@@ -913,13 +913,13 @@ void testJavaAgentWithOptionParsing(@TempDir File output) throws IOException {
 
 		String result = run.generateCommandLine(main);
 
+		if (main.getArgs() != null) {
```
Comment (maxandersen) [inline src/test/java/dev/jbang/cli/TestRun.java:916]: this does not seem to test anything ? is this test generating a big command line ?

Comment (tivrfoa) [reply src/test/java/dev/jbang/cli/TestRun.java]: Removed. Related to previous comment.

File: src/main/java/dev/jbang/Script.java (hunk 2 above)
Comment (tivrfoa) [reply src/main/java/dev/jbang/Script.java]: Removed.
It was because I was not limiting by length. So I needed for the test.

File: src/main/java/dev/jbang/cli/Run.java (hunk 1 above)
Comment (tivrfoa) [reply src/main/java/dev/jbang/cli/Run.java]: Done.
