### PR TITLE
fix: export gradle, add support for Groovy and Kotlin projects

### LINKED ISSUE #1962: build.gradle: add support for Groovy and Kotlin
**Describe the bug**
`jbang export gradle App.kt` fails to create a  build.gradle file that can build and run the JBang Kotlin app.

**JBang version**
0.125.0

### PR DESCRIPTION
**Pull request by wfouche**
Closes #1962

### CODE REVIEW

File: src/main/java/dev/jbang/cli/Export.java [hunk 1]
```diff
@@ -564,7 +564,8 @@ private void createProjectForExport(BuildContext ctx, Path projectDir) throws IO
 		Util.mkdirs(projectDir);
 
 		// Sources
-		Path srcJavaDir = projectDir.resolve("src/main/java");
+		boolean isKotlin = ctx.getProject().getMainClass().endsWith("Kt");
```
Comment (maxandersen) [inline src/main/java/dev/jbang/cli/Export.java:567]: this doesn't feel like a great way to detect wether the project is a kotlin project.

`jbang Kt.java` isn't kotlin :)

```suggestion
		boolean isKotlin = cts.getProject().getMainSource() instanceof KotlinSource;
```

File: src/main/java/dev/jbang/cli/Export.java [hunk 2]
```diff
@@ -653,20 +654,23 @@ void renderBuildFile(BuildContext ctx, Path projectDir, String fullClassName) th
 		Template template = engine.getTemplate(templateRef);
 		if (template == null)
 			throw new ExitException(EXIT_INVALID_INPUT, "Could not locate template named: '" + templateRef + "'");
+		boolean isKotlin = ctx.getProject().getMainClass().endsWith("Kt");
```
Comment (maxandersen) [inline src/main/java/dev/jbang/cli/Export.java:657]: should be updated to use same test as above.

File: src/main/java/dev/jbang/cli/Export.java [hunk 3]
```diff
@@ -653,20 +654,23 @@ void renderBuildFile(BuildContext ctx, Path projectDir, String fullClassName) th
...
 		String result = template
 								.data("group", group)
 								.data("artifact", artifact)
 								.data("version", version)
+								.data("kotlin", isKotlin ? "yes" : "no")
```
Comment (maxandersen) [inline src/main/java/dev/jbang/cli/Export.java:662]: should this be a "language" with java|kotlin|groovy value?

File: src/main/java/dev/jbang/cli/Export.java [hunk 4]
```diff
@@ -653,20 +654,23 @@ void renderBuildFile(BuildContext ctx, Path projectDir, String fullClassName) th
...
 								.data("description", prj.getDescription().orElse(""))
 								.data("repositories", repositories	.stream()
 																	.map(MavenRepo::getUrl)
 																	.filter(s -> !"".equals(s))
 																	.collect(Collectors.toList()))
 								.data("javaVersion", getJavaVersion(prj, false))
 								.data("gradledependencies", gradleify(depIds))
-								.data("fullClassName", fullClassName)
+								.data("fullClassName", fullClassName + (isKotlin ? "Kt" : ""))
```
Comment (maxandersen) [inline src/main/java/dev/jbang/cli/Export.java:670]: sholdn't this not already have Kt in its name at this stage?

File: src/main/resources/export-build.qute.gradle [hunk 5]
```diff
@@ -1,5 +1,10 @@
 plugins {
+{#if kotlin eq 'no'}
 	id 'java'
+{/if}
+{#if kotlin eq 'yes'}
+	id 'org.jetbrains.kotlin.jvm' version '2.0.21'
```
Comment (maxandersen) [inline src/main/resources/export-build.qute.gradle:6]: 2.1.20 seems the latest?

File: src/main/java/dev/jbang/cli/Export.java (hunk 3 above)
Comment (wfouche) [reply src/main/java/dev/jbang/cli/Export.java]: Fixed

File: src/main/java/dev/jbang/cli/Export.java (hunk 4 above)
Comment (wfouche) [reply src/main/java/dev/jbang/cli/Export.java:670]: A Kotlin class called App is translated to Java byte as class AppKt.class.  So the addition of "Kt" is correct.

File: src/main/resources/export-build.qute.gradle (hunk 5 above)
Comment (wfouche) [reply src/main/resources/export-build.qute.gradle]: Fixed

File: src/main/java/dev/jbang/cli/Export.java (hunk 2 above)
Comment (wfouche) [reply src/main/java/dev/jbang/cli/Export.java]: Fixed

File: src/main/java/dev/jbang/cli/Export.java (hunk 1 above)
Comment (wfouche) [reply src/main/java/dev/jbang/cli/Export.java]: Fixed

**Comment by wfouche** [comment]
"The failing job indicates that two tests, testImplictURLAlias and testImplictExplicitURLAlias, failed due to an inability to download a catalog from https://xam.dk/jbang-catalog.json. The error suggests that the URL is either incorrect or the resource is unavailable."

**Comment by wfouche** [comment]
@maxandersen , `./gradlew test` works on my dev machine with the latest submitted code changes, but the some tests fail when run via Github Actions.

**Comment by quintesse** [comment]
> "The failing job indicates that two tests, ...."

That was a temporary problem. Restarting the action fixed it.

**Comment by wfouche** [comment]
Added support for Grooy projects.

**Review by maxandersen — APPROVED** [review]

**Comment by maxandersen** [comment]
overall good - before merging - want to add some basic tests to verify it working as expected in future too?

**Comment by wfouche** [comment]
@maxandersen , would prefer that you merge this pull request as is. 

I'll work on a separate pull request with valdation tests, and submit it when its ready.
