### PR TITLE
fix: add missing "/" before jbang-catalog.json

### LINKED ISSUE #2380: Error resolving hello@acme~experimental
`jbang hello@acme~experimental`  resolves to 

- `https://...../HEAD/experimentaljbang-catalog.json`

and it should resolve to

- `https://...../HEAD/experimental/jbang-catalog.json`

### PR DESCRIPTION
**Pull request by wfouche**
Fixes #2380

### CODE REVIEW

**Comment by maxandersen** [comment]
hmm - not sure what this is fixing?
got a test that fails we can add?

**Comment by wfouche** [comment]
https://www.jbang.dev/documentation/jbang/latest/alias_catalogs.html

The advertised support for 

- jbang hello@acme~experimental
- hello found in acme/jbang-catalog/experimental/jbang-catalog.json

does not work without this PR.

The alias is resolved to acme/jbang-catalog/**experimentaljbang**-catalog.json with a missing '/' before jbang-catalog.json 

I'll gladly add a testcase, just tell me to which file I should add it and roughly how it should work.

**Comment by maxandersen** [comment]
yeah was just looking - and it should have been in TestImplicitAlias but it does not seem to test implicit catalog much at all. so yeah, definitely should expand that one ;)

**Comment by wfouche** [comment]
@quintesse , I reverted a change that you made to remove '/' if it was at the end of the path string. Maybe it was just debug code that you wrote and inadvertently submitted, or did it serve a real purpose? The test cases are not affected by this revert, but it does fix how "hello@acme~experimental" is resolved.

**Comment by maxandersen** [comment]
@wfouche what pr/commit did the original change?

in any case, should add test for this in TestImplicitAlias so we dont loose it again :)

**Comment by wfouche** [comment]
> @wfouche what pr/commit did the original change?

See changes made to file ImplicitCatalogRef.java by https://github.com/jbangdev/jbang/pull/1743/changes#diff-596ddf206078ca715256b4ea770cd920ab1e5c64908d43f912b47e81f720e180

- this.path = path.endsWith("/") ? path.substring(0, path.length() - 1) : path

> in any case, should add test for this in TestImplicitAlias so we dont loose it again :)

Yes.

**Comment by wfouche** [comment]
@maxandersen , 

- ImplicitCatalogRef.resolveImplicitCatalogUrl("jbangdev/jbang-examples").get() is resolved correctly, but
- ImplicitCatalogRef.resolveImplicitCatalogUrl("jbangdev~experimental").get() return a null value.

I don't have time to go too deep into this at the moment, but will create a new issue to for this to be fixed and a proper testcase to be created for jbangdev~jbang-examples.

**Comment by wfouche** [comment]
Related issue #2383

**Comment by maxandersen** [comment]
What would double ~ mean ?

**Comment by wfouche** [comment]
I've updated the examples to eliminate any visual confusion it might have caused.  There is no double ~ , just a single ~ is being used.

**Comment by wfouche** [comment]
@maxandersen , this PR is ready to be reviewed.

**Comment by maxandersen** [comment]
@wfouche thanks - i'm seeing one change, no test to catch we dont break again - were you not adding a test to TestImplicitAlias?

**Comment by wfouche** [comment]
@maxandersen , in the end I only reverted an earlier change that was made which broke the acme~experimental functionality. It would be great if you can merge the fix as is (and release a new version of JBang).

I spend time trying to create an additional test case, but the code is rather complex, hard to understand and the seemingly simple test case just did not work. After debugging for a while, I suspended the effort. But I did create issue https://github.com/jbangdev/jbang/issues/2383 for us to remember to follow up and create the required test case.

**Comment by maxandersen** [comment]
What is the actually issue this final bugfix fixes? I'll add a test for it.

**Comment by wfouche** [comment]
@maxandersen , the issue is easy to reproduce.

Just run `jbang --verbose hello@jbangdev~experimental`
....
[jbang] [4:106] Requesting HTTP GET https://gitlab.com/jbangdev/jbang-catalog/-/raw/HEAD/experimentaljbang-catalog.json

**experimentaljbang-catalog.json** is the issue, with the fix it is resolved to **experimental/jbang-catalog.json**

I also run the following app during testing.

```java
//DEPS dev.jbang:jbang.bin:0.136.0

//JAVA 21

import static java.lang.System.*;

import dev.jbang.catalog.Alias;
import dev.jbang.catalog.ImplicitCatalogRef;

public class hello {

    public static void main(String... args) {
        var s = "jbangdev";
        var z = ImplicitCatalogRef.resolveImplicitCatalogUrl(s).get();
        out.println(z.toString());

        s = "jbangdev/jbang-examples";
        z = ImplicitCatalogRef.resolveImplicitCatalogUrl(s).get();
        out.println(z.toString());

        s = "jbangdev~experimental";
        z = ImplicitCatalogRef.resolveImplicitCatalogUrl(s).get();
        out.println(z.toString());
    }
}
```

**Comment by wfouche** [comment]
@maxandersen . I created a test case but it is not working 100%. Maybe you can spot the error and fix it.

I'm using the following hello app as part of the test:

- https://github.com/wfouche/jbang-catalog/tree/main/hello

It would be best to move it to the **jbangdev/jbang-catalog** repo, if it is to remain part of the test.

File: src/test/java/dev/jbang/cli/TestRun.java [hunk 1]
```diff
@@ -390,6 +391,43 @@ void testJarViaHttps(@TempDir Path tdir) throws IOException {
 		}
 	}
 
+	@Test
```
Comment (quintesse) [inline src/test/java/dev/jbang/cli/TestRun.java]: This seems like an insanely complex test for such a simple change :-)
I would suggest just adding a simple test to `TestImplicitAlias` where you test directly that the class returns what it is supposed to return.

File: src/main/java/dev/jbang/catalog/ImplicitCatalogRef.java [hunk 2]
```diff
@@ -27,7 +27,7 @@ private ImplicitCatalogRef(String org, String repo, String ref, String path) {
 		this.org = org;
 		this.repo = repo;
 		this.ref = ref;
-		this.path = path.endsWith("/") ? path.substring(0, path.length() - 1) : path;
+		this.path = path;
```
Comment (quintesse) [inline src/main/java/dev/jbang/catalog/ImplicitCatalogRef.java]: Let's first get a better test. But I'm not sure this is the correct fix.
The reason this line is here is to make sure that the path is always in a known format (in this case we known that it will never end in a slash) which makes it easier to build full URLs with it by simply concatenating strings.
So my preference would be in making changes to the code that creates URLs (like in the `repoUrl()` or `toString() methods).

**Review by quintesse — CHANGES_REQUESTED** [review]

File: src/main/java/dev/jbang/catalog/ImplicitCatalogRef.java (hunk 2 above)
Comment (wfouche) [reply src/main/java/dev/jbang/catalog/ImplicitCatalogRef.java]: Thanks @quintesse . I reverted the this.path update and fixed repoUrl().

File: src/main/java/dev/jbang/catalog/ImplicitCatalogRef.java [hunk 3]
```diff
@@ -31,7 +31,13 @@ private ImplicitCatalogRef(String org, String repo, String ref, String path) {
 	}
 
 	private String repoUrl(String host, String infix) {
-		return host + org + "/" + repo + infix + ref + "/" + path + Catalog.JBANG_CATALOG_JSON;
+		String fs = "";
+		if (!path.isEmpty()) {
```
Comment (quintesse) [inline src/main/java/dev/jbang/catalog/ImplicitCatalogRef.java]: Well, we already know that path doesn't end with a "/", the constructor makes sure of that, so the second if isn't necessary :-)

And perhaps write it like:

```
String fs = !path.isEmpty() ? "/" : "";
```

**Review by quintesse — CHANGES_REQUESTED** [review]

File: src/main/java/dev/jbang/catalog/ImplicitCatalogRef.java (hunk 3 above)
Comment (wfouche) [reply src/main/java/dev/jbang/catalog/ImplicitCatalogRef.java]: Fixed.

**Comment by wfouche** [comment]
@maxandersen , finally we have a simple & working test case!  :-)

**Review by quintesse — COMMENTED** [review]
LGTM 👍

**Review by quintesse — APPROVED** [review]
Stupid UI. It changed my Approve back to Comment just when I hit Submit.

**Comment by quintesse** [comment]
Thanks @wfouche !
