### PR TITLE
fix: fixed problem `--deps` and `//REPOS`

### LINKED ISSUE #1292: Dependency resolving error with custom maven repo, multiple runs and a "--deps" declaration
**Describe the bug**
Calling jbang is failing.

The context:

* We run `./jbang info tools`
* We have a custom company maven repo
* We use `RELEASE` as version definition (to get the latest release)

I think the issue depends of the state of the local maven repo (working on this to be sure)

**To Reproduce**

The script `myJangScript` has an custom company repo (which aggregates a maven-central mirror and a company maven repo).
Something like:

```
//REPOS acme=https://maven.acme.local/maven
```

We would like to use the latest version of `company-lib`

Therefore we are passing `--deps company.group.id:company-lib:RELEASE`.

In some situations (that I am trying to reproduce now), we have this error:

```
+ ./jbang info tools --verbose --deps company.group.id:company-lib:RELEASE myJangScript
 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
 [jbang] jbang version 0.91.0
 [jbang] System Java version detected as 8
 [jbang] System Java version matches requested version 8
 [jbang] Resolving dependencies...
 [jbang] company.group.id:company-lib:jar:RELEASE
 [jbang] [ERROR] Could not resolve dependencies from mavencentral=https://repo1.maven.org/maven2/
 Unable to collect/resolve dependency tree for a resolution due to: Failed to collect dependencies at company.group.id:company-lib:jar:RELEASE, caused by: Could not find metadata company.group.id:company-lib/maven-metadata.xml in local (/var/lib/jenkins/.m2/repository)
   Failed to collect dependencies at company.group.id:company-lib:jar:RELEASE
 dev.jbang.cli.ExitException: Could not resolve dependencies from mavencentral=https://repo1.maven.org/maven2/
 Unable to collect/resolve dependency tree for a resolution due to: Failed to collect dependencies at company.group.id:company-lib:jar:RELEASE, caused by: Could not find metadata company.group.id:company-lib/maven-metadata.xml in local (/var/lib/jenkins/.m2/repository)
   Failed to collect dependencies at company.group.id:company-lib:jar:RELEASE
 	at dev.jbang.dependencies.DependencyUtil.resolveDependenciesViaAether(DependencyUtil.java:254)
 	at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:122)
 	at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:71)
 	at dev.jbang.dependencies.DependencyResolver.resolve(DependencyResolver.java:67)
 	at dev.jbang.source.RunContext.resolveClassPath(RunContext.java:354)
 	at dev.jbang.cli.BaseInfoCommand$ScriptInfo.<init>(Info.java:95)
 	at dev.jbang.cli.BaseInfoCommand.getInfo(Info.java:163)
 	at dev.jbang.cli.Tools.doCall(Info.java:186)
 	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:93)
 	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:15)
 	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
 	at picocli.CommandLine.access$1300(CommandLine.java:145)
 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
 	at dev.jbang.cli.JBang$3.handle(JBang.java:145)
 	at dev.jbang.cli.JBang$3.handle(JBang.java:140)
 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
 	at picocli.CommandLine.execute(CommandLine.java:2078)
 	at dev.jbang.Main.main(Main.java:14)
 Caused by: org.jboss.shrinkwrap.resolver.api.NoResolvedResultException: Unable to collect/resolve dependency tree for a resolution due to: Failed to collect dependencies at company.group.id:company-lib:jar:RELEASE, caused by: Could not find metadata company.group.id:company-lib/maven-metadata.xml in local (/var/lib/jenkins/.m2/repository)
 	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.wrapException(MavenWorkingSessionImpl.java:503)
 	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.resolveDependencies(MavenWorkingSessionImpl.java:242)
 	at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.using(MavenStrategyStageBaseImpl.java:70)
 	at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.withTransitivity(MavenStrategyStageBaseImpl.java:52)
 	at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.withTransitivity(MavenStrategyStageBaseImpl.java:39)
 	at dev.jbang.dependencies.DependencyUtil.resolveDependenciesViaAether(DependencyUtil.java:232)
 	... 18 more
 Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at company.group.id:company-lib:jar:RELEASE
 	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:353)
 	at org.jboss.shrinkwrap.resolver.impl.maven.bootstrap.MavenRepositorySystem.resolveDependencies(MavenRepositorySystem.java:121)
 	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.resolveDependencies(MavenWorkingSessionImpl.java:239)
 	... 22 more
 Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at company.group.id:company-lib:jar:RELEASE
 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
 	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309)
 	... 24 more
 Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for company.group.id:company-lib:jar:RELEASE
 	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:218)
 	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171)
 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:541)
 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:524)
 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:412)
 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:365)
 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:352)
 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
 	... 25 more
 Caused by: org.eclipse.aether.resolution.VersionResolutionException: Failed to resolve version for company.group.id:company-lib:jar:RELEASE: Could not find metadata company.group.id:company-lib/maven-metadata.xml in local (/var/lib/jenkins/.m2/repository)
 	at org.apache.maven.repository.internal.DefaultVersionResolver.resolveVersion(DefaultVersionResolver.java:276)
 	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:204)
 	... 32 more
 Caused by: org.eclipse.aether.transfer.MetadataNotFoundException: Could not find metadata company.group.id:company-lib/maven-metadata.xml in local (/var/lib/jenkins/.m2/repository)
 	at org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolve(DefaultMetadataResolver.java:220)
 	at org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolveMetadata(DefaultMetadataResolver.java:181)
 	at org.apache.maven.repository.internal.DefaultVersionResolver.resolveVersion(DefaultVersionResolver.java:213)
 	... 33 more
 [jbang] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
```

**Expected behavior**
The call works, I will post a example where it works (other Jenkins worker where the local maven repo is not the same)

**JBang version**
0.91.0

**Additional context**

First wired thing, this looks really wrong:

`[ERROR] Could not resolve dependencies from mavencentral=https://repo1.maven.org/maven2/`

For me jbang should use the repo defined in the source.

Is it different if I run `./jbang run` vs `./jbang info tools`

### PR DESCRIPTION
**Pull request by quintesse**
If the code had `//REPOS` tags and it would get run with `--deps`
on the command line then those deps would not get resolved against
the repostories mentioned in the `//REPOS` tags if no build was being
performed.

Fixes #1292

### CODE REVIEW

File: src/test/java/dev/jbang/cli/TestRun.java [hunk 1]
```diff
@@ -643,21 +643,6 @@ void testURLPrepareDoesNotExist() throws IOException {
 		assertThrows(ExitException.class, () -> RunContext.empty().forResource(url));
 	}
 
-	@Test
-	void testFindMain(@TempDir Path dir) throws IOException {
```
Comment (maxandersen) [inline src/test/java/dev/jbang/cli/TestRun.java:647]: why remove this test? shouldn't it just be changed to use a source?

Comment (quintesse) [reply src/test/java/dev/jbang/cli/TestRun.java:647]: It was testing a method that was not being used anymore and was removed.

Comment (maxandersen) [reply src/test/java/dev/jbang/cli/TestRun.java:647]: hmm - so that is actually unrelated to the issue - just old dead code?

**Review by maxandersen — APPROVED** [review]
lgtm but please rebase first.

File: src/test/java/dev/jbang/cli/TestRun.java (hunk 1 above)
Comment (quintesse) [reply src/test/java/dev/jbang/cli/TestRun.java:647]: Not entirely unrelated. I changed some things related to the handling of main class and noticed the unused methods.

**Comment by quintesse** [comment]
Rebased.
