### PR TITLE
fix: verbose will now report why build is happening

### LINKED ISSUE #1189: JBang always recompiling the scripts
**Describe the bug**

For a month or so now, JBang is always recompiling my JBang scripts and I always get the following output when executing my JBang script:
```
[jbang] Building jar...
[jbang] Post build with io.quarkus.launcher.JBangIntegration
Jan 10, 2022 5:44:25 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.4.2.Final
Jan 10, 2022 5:44:25 PM io.quarkus.deployment.QuarkusAugmentor run
INFO: Quarkus augmentation completed in 585ms
```

**To Reproduce**

No idea how to reproduce it outside of my environment. Things were working (i.e. it compiled the scripts only when I changed them) and then it started recompiling them for each execution.

It might be a coincidence but I think it started when I got JBang telling me that there was a new version around and that I should update.

I have this behavior for all the scripts of the Quarkus release process:
https://github.com/quarkusio/quarkus-release/blob/main/prerequisites.java

That I execute for instance with:
```
jbang --verbose prerequisites.java --micro --branch=2.2
```

I haven't updated nor removed the cache as I thought it might be useful to keep things this way.

**JBang version**

```
[jbang] jbang version 0.70.0
Cache: /home/gsmet/.jbang/cache
Config: /home/gsmet/.jbang
Repository:/home/gsmet/.m2/repository
0.70.0
```

### PR DESCRIPTION
**Pull request by maxandersen**
fixes #1189

### CODE REVIEW

File: src/main/java/dev/jbang/cli/BaseBuildCommand.java [hunk 1]
```diff
@@ -106,21 +106,39 @@ static Source build(ScriptSource src, RunContext ctx) throws IOException {
...
-			if (jarSrc == null
-					|| !jarSrc.isUpToDate()
-					|| JavaUtil.javaVersion(requestedJavaVersion) < JavaUtil.minRequestedVersion(
-							jarSrc.getJavaVersion())) {
+
+			if (jarSrc == null) {
+				Util.verboseMsg("Building as previous built jar not found.");
+				buildRequired = true;
+			} else if (!jarSrc.isUpToDate()) {
+				Util.verboseMsg("Building as previous build jar found but it or its dependencies not uptodate.");
```
Comment (quintesse) [inline src/main/java/dev/jbang/cli/BaseBuildCommand.java:124]: I'd write "up-to-date" here

**Review by quintesse — APPROVED** [review]
LGTM (except for that one word change)

File: src/main/java/dev/jbang/cli/BaseBuildCommand.java (hunk 1 above)
Comment (maxandersen) [inline src/main/java/dev/jbang/cli/BaseBuildCommand.java:124]:
```suggestion
				Util.verboseMsg("Building as previous build jar found but it or its dependencies not up-to-date.");
```
