### PR TITLE
fix: Improved `main()` method lookup

### LINKED ISSUE #1099: "Could not locate unique class. Found 0 candidates." when the first class does have main method.
To reproduce, take this gist:
  https://gist.github.com/ge0ffrey/9f4c558347f128790e774223f4a63fb3
And run it on:
  https://www.jdoodle.com/try-jbang

### PR DESCRIPTION
**Pull request by quintesse**
Before it would just assume that the `main()` method was located
in a class with the same name as the Java source file, but that's
not always the case. For example, when reading from stdin it's
hard to detect the right class and even more so when dealing with
non-public classes (non-public classes can still have `main()`
methods!)

Fixes #1099

### CODE REVIEW

File: src/test/java/dev/jbang/cli/TestRun.java [hunk 1]
```diff
@@ -1250,6 +1250,30 @@ void multiSourcesHttp() throws IOException {
 
 	}
 
+	String script = "" +
+			"class One {\n" +
+			"}" +
+			"class Two {\n" +
+			"public static void main(String... args) { };\n" +
```
Comment (maxandersen) [inline src/test/java/dev/jbang/cli/TestRun.java:1257]: when I remove this line the test still passes so its not actually testing the issue.

Comment (maxandersen) [reply src/test/java/dev/jbang/cli/TestRun.java:1257]: i.e. building is not the issue running is.

File: src/main/java/dev/jbang/cli/BaseBuildCommand.java [hunk 2]
```diff
@@ -411,56 +412,47 @@ protected static void searchForMain(ScriptSource src, RunContext ctx, File tmpJa
...
-
-					if (src.isAgent()) {
+				List<ClassInfo> mains = classes	.stream()
+												.filter(src.getMainFinder())
+												.collect(Collectors.toList());
+				String mainName = src.getSuggestedMain();
+				if (mains.size() > 1 && mainName != null) {
+					mains = mains.stream().filter(ci -> ci.simpleName().equals(mainName)).collect(Collectors.toList());
+				}
+				if (mains.size() > 1) {
```
Comment (maxandersen) [inline src/main/java/dev/jbang/cli/BaseBuildCommand.java:433]: can also be 0 so should be != as in previous version.

File: src/test/java/dev/jbang/cli/TestRun.java (hunk 1 above)
Comment (maxandersen) [reply src/test/java/dev/jbang/cli/TestRun.java:1257]: actually it is build that is the issue but code and test doesn't catch it . i'll update the pr

File: src/main/java/dev/jbang/cli/BaseBuildCommand.java (hunk 2 above)
Comment (maxandersen) [reply src/main/java/dev/jbang/cli/BaseBuildCommand.java:433]: actually if class is an agent it might be ok...

**Comment by maxandersen** [comment]
not following how the build can fail ....works perfectly when I check it out.

**Comment by maxandersen** [comment]
@quintesse can you confirm wether it fails for you too or github action being dumb?

**Comment by quintesse** [comment]
@maxandersen no problem here, tried with Java 8 and 11

**Comment by maxandersen** [comment]
GitHub actions, go home. you're drunk.

**Comment by quintesse** [comment]
Hmmm... I just rebased against `main` locally and then I get the same errors (because the API has changed and your new tests haven't been updated yet). I just don't understand how that is happening though, the build should be against the PR code

**Comment by quintesse** [comment]
Warning @maxandersen : I'm going to do a force-push of the rebase code !!

**Comment by quintesse** [comment]
Well that seems to have "fixed" things 🤷‍♂️

**Comment by quintesse** [comment]
DId you cancel @maxandersen or did something go wrong during the CI?

**Comment by maxandersen** [comment]
Im making danish xmas food atm so it wasn't me.

**Comment by quintesse** [comment]
Hmmm, is it already xmas overthere? :-)

**Comment by maxandersen** [comment]
> Hmmm, is it already xmas overthere? :-)

It's December. It's Xmas 24-7
