### PR TITLE
fix: Default alias name when creating a new alias

### LINKED ISSUE #374: alias add -f directory should create jbang-catalog.json in that directory
would be nice to just go:

`jbang alias -f . xyz path/to/xyz.java`

instead of having to spell out jbang-catalog.json.

right now the above gives: `[jbang] [WARN] Unable to add alias: /Users/max/code/camel-visual/.: Is a directory`

### PR DESCRIPTION
**Pull request by chrsblck**
fixes #374

### CODE REVIEW

**Comment by chrsblck** [comment]
@quintesse @maxandersen This is ready for review, thanks!

File: src/main/java/dev/jbang/cli/Alias.java [hunk 1]
```diff
@@ -28,6 +30,8 @@
 	protected Path getCatalog() {
 		if (global) {
 			return Settings.getAliasesFile();
+		} else if (catalogFile != null && Files.isDirectory(catalogFile)) {
```
Comment (quintesse) [inline src/main/java/dev/jbang/cli/Alias.java:33]: Almost, we still need to check for the `catalogFile/.jbang/jbang-catalog.json` file as well. Also remember that in case that the file doesn't exist we still need to return `catalogFile/jbang-catalog.json` so `alias add` knows what file to.

**Review by quintesse — CHANGES_REQUESTED** [review]

File: src/main/java/dev/jbang/cli/Alias.java (hunk 1 above)
Comment (chrsblck) [reply src/main/java/dev/jbang/cli/Alias.java:33]: Oops 🤦

Comment (chrsblck) [reply src/main/java/dev/jbang/cli/Alias.java:33]: @quintesse Fixed.

**Review by quintesse — APPROVED** [review]
Looks good!

**Comment by chrsblck** [comment]
Let me know if you want me to squash the changes, or maybe the GitHub `squash and merge` is enough

**Comment by maxandersen** [comment]
perfect! thanks @chrsblck !
